server:
  port: 8820

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalCors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
            maxAge: 3600

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-service:8760/eureka
