server.port=8760

spring.application.name=discovery-service

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

eureka.client.serviceUrl.defaultZone=http://discovery-service:8760/eureka

eureka.instance.hostname=discovery-service

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
