-- ============================================================================
-- LINEA BASE: el esquema TAL Y COMO ESTA HOY
-- ============================================================================
--
-- Este fichero no inventa nada. Es el DDL que Hibernate venia generando con
-- ddl-auto=update, volcado tal cual, para que la base de datos deje de
-- depender de lo que Hibernate decida hacer al arrancar.
--
-- IMPORTANTE: sobre la base de datos de desarrollo, que YA tiene las tablas y
-- datos reales, este fichero NO se ejecuta: baseline-on-migrate=true marca la
-- version 1 como ya aplicada y Flyway sigue por la V2. Solo corre entero en
-- una base de datos nueva (una instalacion limpia o el H2 de las pruebas).
--
-- Un detalle: en la base que creo ddl-auto=update las claves llevan bigserial
-- (columna + secuencia); aqui se declaran GENERATED BY DEFAULT AS IDENTITY,
-- que es lo mismo para Hibernate y para la validacion del esquema y ademas
-- vale igual en PostgreSQL y en H2. Solo se nota en una instalacion nueva; la
-- base que ya existe conserva sus secuencias intactas porque este fichero no
-- corre sobre ella.
--
-- Las clausulas CHECK de los enums son las que genera Hibernate: si algun dia
-- se anade un valor a CategoryType o a Frequency, hace falta una migracion
-- nueva que las actualice, porque aqui no se van a regenerar solas.
-- ============================================================================

CREATE TABLE oc_budget_household (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    active     BOOLEAN      NOT NULL,
    created_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_budget_household_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    household_id BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    role         VARCHAR(20) NOT NULL,
    active       BOOLEAN     NOT NULL,
    created_at   TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_budget_category (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(255),
    parent_id    BIGINT,
    icon         VARCHAR(50),
    color        VARCHAR(7),
    household_id BIGINT,
    type         VARCHAR(255) NOT NULL CHECK (type IN ('INCOME', 'EXPENSE')),
    active       BOOLEAN      NOT NULL,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_budget_movement (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id               BIGINT        NOT NULL,
    category_id           BIGINT        NOT NULL,
    date                  DATE          NOT NULL,
    amount                NUMERIC(15, 2) NOT NULL,
    description           VARCHAR(255),
    scheduled_movement_id BIGINT,
    period_start          DATE,
    parent_movement_id    BIGINT,
    is_transfer           BOOLEAN       NOT NULL,
    transfer_pair_id      BIGINT,
    confirmed             BOOLEAN       NOT NULL,
    active                BOOLEAN       NOT NULL,
    created_at            TIMESTAMP(6),
    updated_at            TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_budget_scheduled_movement (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT       NOT NULL,
    category_id     BIGINT       NOT NULL,
    name            VARCHAR(100) NOT NULL,
    amount          NUMERIC(15, 2),
    frequency       VARCHAR(255) NOT NULL CHECK (frequency IN
                        ('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY',
                         'BIMONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL')),
    duration_months INTEGER,
    start_date      DATE         NOT NULL,
    end_date        DATE,
    day_of_month    INTEGER,
    active          BOOLEAN      NOT NULL,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_budget_allocation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT         NOT NULL,
    category_id      BIGINT         NOT NULL,
    household_id     BIGINT,
    period_start     DATE           NOT NULL,
    period_end       DATE           NOT NULL,
    allocated_amount NUMERIC(15, 2) NOT NULL,
    status           VARCHAR(20)    NOT NULL,
    notes            VARCHAR(255),
    active           BOOLEAN        NOT NULL,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX idx_hm_user ON oc_budget_household_member (user_id);
CREATE INDEX idx_hm_household ON oc_budget_household_member (household_id);
CREATE INDEX idx_category_user_active ON oc_budget_category (user_id, active);
CREATE INDEX idx_category_user_parent_active ON oc_budget_category (user_id, parent_id, active);
CREATE INDEX idx_movement_user_date_active ON oc_budget_movement (user_id, date, active);
CREATE INDEX idx_movement_user_confirmed_active ON oc_budget_movement (user_id, confirmed, active);
CREATE INDEX idx_scheduled_user_active ON oc_budget_scheduled_movement (user_id, active);
CREATE INDEX idx_allocation_user_period ON oc_budget_allocation (user_id, period_start);
CREATE INDEX idx_allocation_household_period ON oc_budget_allocation (household_id, period_start);
CREATE INDEX idx_allocation_category_period ON oc_budget_allocation (category_id, period_start);
