-- =====================================================================
-- V4 — Cuentas, y el reparto de lo que ya existe
-- =====================================================================
--
-- Aparece la pregunta que la app nunca supo responder: DONDE esta la plata.
-- Hasta ahora un movimiento decia cuanto y de que, pero no de que bolsillo
-- salio, asi que no habia forma de afirmar "en tu cuenta hay 1.240.000" y que
-- el banco lo confirmara o lo desmintiera.
--
-- TRES DECISIONES QUE SE VEN EN ESTE FICHERO
--
--  1. NO HAY COLUMNA DE SALDO. Se calcula sumando los movimientos, siempre.
--     Un saldo guardado puede quedar desincronizado de los movimientos que
--     resume, y cuando pasa no hay manera de saber cual de los dos miente.
--
--  2. NO HAY COLUMNA DE SALDO INICIAL. El saldo de partida es un MOVIMIENTO
--     con su fecha (is_opening). Asi se puede calcular el saldo de cualquier
--     dia, que es lo que hace falta para conciliar contra un extracto viejo.
--
--  3. account_id SE QUEDA NULABLE. Al terminar esta migracion no habra ni un
--     movimiento sin cuenta —el bloque de abajo los reparte todos—, pero si la
--     columna fuera NOT NULL, un cliente antiguo que no mande accountId
--     recibiria un error de base de datos en lugar de guardar. La garantia se
--     pone en el servicio, que asigna la cuenta por defecto, y la vigila una
--     prueba. Mejor una respuesta util que una excepcion.

CREATE TABLE IF NOT EXISTS oc_budget_account (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    name         VARCHAR(100) NOT NULL,
    kind         VARCHAR(20)  NOT NULL CHECK (kind IN ('OWN', 'LIABILITY')),
    icon         VARCHAR(50),
    color        VARCHAR(7),
    household_id BIGINT,
    is_default   BOOLEAN      NOT NULL,
    active       BOOLEAN      NOT NULL,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_account_user_active
    ON oc_budget_account (user_id, active);
CREATE INDEX IF NOT EXISTS idx_account_household_active
    ON oc_budget_account (household_id, active);

ALTER TABLE oc_budget_movement
    ADD COLUMN IF NOT EXISTS account_id BIGINT;

ALTER TABLE oc_budget_movement
    ADD COLUMN IF NOT EXISTS is_opening BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_movement_account_date_active
    ON oc_budget_movement (account_id, date, active);

-- ---------------------------------------------------------------------
-- El reparto de lo que ya existe
-- ---------------------------------------------------------------------
--
-- Una cuenta "Sin asignar" por cada persona que tenga movimientos, y todos sus
-- movimientos dentro.
--
-- Se hace asi y no pidiendole al usuario que clasifique porque nadie va a
-- repasar cuatrocientos movimientos para poder volver a abrir la app. La
-- cuenta por defecto es una cuenta normal: se puede renombrar y usar como la
-- de diario. Lo unico que no se puede es borrarla mientras existan movimientos
-- que no digan en que cuenta ocurrieron.
--
-- Solo se crea para quien TIENE movimientos: a un usuario nuevo se la creara
-- el servicio cuando la necesite, y no tiene sentido dejarle una cuenta
-- llamada "Sin asignar" en una app recien estrenada.

INSERT INTO oc_budget_account (user_id, name, kind, icon, color, is_default, active, created_at, updated_at)
SELECT DISTINCT m.user_id,
       'Sin asignar',
       'OWN',
       'help-circle-outline',
       '#90A4AE',
       TRUE,
       TRUE,
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP
FROM oc_budget_movement m
WHERE NOT EXISTS (
    SELECT 1 FROM oc_budget_account a
    WHERE a.user_id = m.user_id AND a.is_default = TRUE AND a.active = TRUE
);

UPDATE oc_budget_movement m
SET account_id = (
    SELECT a.id FROM oc_budget_account a
    WHERE a.user_id = m.user_id AND a.is_default = TRUE AND a.active = TRUE
)
WHERE m.account_id IS NULL;
