-- =====================================================================
-- V6 — El reparto de un gasto entre varias personas
-- =====================================================================
--
-- LA REGLA DE ORO, que es lo unico que hay que entender de esta tabla:
--
--   Un gasto de 120.000 que pagaste tu y se reparte entre tres personas son
--   120.000 EN TU CUENTA —eso es lo que salio de tu banco y tiene que cuadrar
--   con el extracto— pero solo 40.000 EN TU CATEGORIA, porque eso es lo que
--   gastaste tu. Los otros 80.000 no son gasto: son un derecho de cobro.
--
-- Hoy la app mete los 120.000 en la categoria, y por eso el presupuesto miente
-- cada vez que alguien pone la cuenta del restaurante: se come el mes entero
-- de "Restaurantes" con plata que le van a devolver.
--
-- POR QUE UNA TABLA APARTE Y NO DOS COLUMNAS EN EL MOVIMIENTO
-- -----------------------------------------------------------
-- Porque el reparto es entre N personas y N no se sabe. Con columnas se
-- resuelve el caso de dos y se rompe el de tres, que es exactamente donde esto
-- empieza a valer la pena.
--
-- POR QUE SE GUARDAN DOS VALORES POR PERSONA
-- ------------------------------------------
-- share_value es lo que la persona ESCRIBIO (2 participaciones, 30 %,
-- 45.000...) y computed_amount la plata que sale de ahi. Solo con el calculado
-- no se puede recalcular al cambiar el importe del gasto; solo con el escrito
-- habria que recalcular en cada lectura y los redondeos no siempre coinciden.
-- Se guardan los dos, y computed_amount es la verdad para cualquier suma.

CREATE TABLE IF NOT EXISTS oc_budget_movement_split (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movement_id     BIGINT         NOT NULL,
    user_id         BIGINT         NOT NULL,
    share_value     NUMERIC(15, 4),
    computed_amount NUMERIC(15, 2) NOT NULL,
    active          BOOLEAN        NOT NULL,
    created_at      TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_split_movement
    ON oc_budget_movement_split (movement_id);
CREATE INDEX IF NOT EXISTS idx_split_user_active
    ON oc_budget_movement_split (user_id, active);

-- El modo dice COMO se calculo el reparto. Se guarda para poder recalcular si
-- cambia el importe del gasto; nulo significa "este gasto no se reparte", que
-- es el caso de absolutamente todos los que ya existen.
ALTER TABLE oc_budget_movement
    ADD COLUMN IF NOT EXISTS split_mode VARCHAR(20);

-- La liquidacion ("te paso los 80.000 que te debo") es un movimiento, y NO es
-- ni ingreso ni gasto: la plata solo cambia de dueno. Se marca aparte y no se
-- reutiliza is_transfer porque son dos cosas distintas —la transferencia mueve
-- plata entre bolsillos de la MISMA persona— y mezclarlas obligaria a
-- distinguirlas despues por algun otro campo.
ALTER TABLE oc_budget_movement
    ADD COLUMN IF NOT EXISTS is_settlement BOOLEAN NOT NULL DEFAULT FALSE;

-- Con quien se salda, cuando es una liquidacion.
ALTER TABLE oc_budget_movement
    ADD COLUMN IF NOT EXISTS settled_with_user_id BIGINT;
