-- =====================================================================
-- V8 — Importar el extracto del banco
-- =====================================================================
--
-- POR QUE ESTO ES LO QUE DECIDE SI LA APP SE USA O SE ABANDONA
-- ------------------------------------------------------------
-- Nadie deja una app de finanzas porque los informes sean feos. Todo el mundo
-- la deja por teclear sesenta movimientos al mes. El coste de entrada de datos
-- es lo unico que decide la retencion, y por eso esto vale mas que cualquier
-- grafico.

-- ---------------------------------------------------------------------
-- 1. El identificador que da el banco
-- ---------------------------------------------------------------------
--
-- Cuando el extracto trae una referencia unica de la operacion, es la unica
-- senal fiable de que dos filas son la misma: el importe se repite, la fecha
-- baila y la descripcion la reescribe cualquiera.
--
-- Se guarda en el movimiento para que el cotejo de la SIGUIENTE importacion lo
-- pueda usar. Sin esto, reimportar el mismo mes obliga a adivinar por importe
-- y fecha incluso teniendo el dato exacto delante.
ALTER TABLE oc_budget_movement
    ADD COLUMN IF NOT EXISTS external_id VARCHAR(120);

CREATE INDEX IF NOT EXISTS idx_movement_external
    ON oc_budget_movement (user_id, external_id);

-- ---------------------------------------------------------------------
-- 2. El perfil del banco: en que columna viene cada cosa
-- ---------------------------------------------------------------------
--
-- El importador de Firefly III es una maravilla de configurabilidad y por eso
-- casi nadie llega al final. Aqui se hace la parte que da el 80 % del valor:
-- decir una sola vez que columna es la fecha, cual el importe y cual la
-- descripcion, y que la app lo recuerde POR BANCO.
--
-- Se recuerda por banco y no por usuario a secas porque el mismo usuario
-- exporta de Bancolombia y de Nequi, y los formatos no se parecen en nada.
--
-- Las columnas se guardan por INDICE y no por nombre de cabecera: hay bancos
-- que exportan sin cabecera, y otros que la cambian entre versiones del portal.
CREATE TABLE IF NOT EXISTS oc_budget_import_profile (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id            BIGINT       NOT NULL,
    bank_name          VARCHAR(100) NOT NULL,
    date_column        INTEGER      NOT NULL,
    amount_column      INTEGER      NOT NULL,
    description_column INTEGER,
    external_id_column INTEGER,
    date_pattern       VARCHAR(40),
    decimal_separator  VARCHAR(1),
    has_header         BOOLEAN      NOT NULL,
    /* Hay bancos que exportan los gastos en positivo y en una columna aparte.
       Con esto se invierte el signo al importar en vez de pedirle al usuario
       que edite sesenta filas. */
    invert_sign        BOOLEAN      NOT NULL,
    active             BOOLEAN      NOT NULL,
    created_at         TIMESTAMP(6),
    updated_at         TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_import_profile_user
    ON oc_budget_import_profile (user_id, active);

-- ---------------------------------------------------------------------
-- 3. El diccionario: donde pusiste esto la vez pasada
-- ---------------------------------------------------------------------
--
-- Se aprende solo. Cada vez que confirmas una importacion y le asignas
-- categoria a una fila, se guarda la descripcion normalizada apuntando a esa
-- categoria. La siguiente vez, "COMPRA EXITO CALLE 80" ya viene clasificado.
--
-- La descripcion se guarda NORMALIZADA (sin tildes, minusculas, sin signos)
-- porque el banco escribe en mayusculas y sin tildes, y comparar en crudo
-- convierte cada variante en una entrada distinta que no sirve para nada.
--
-- `hits` no es estadistica: cuando dos reglas compiten por una misma
-- descripcion gana la mas usada, que es casi siempre la correcta.
CREATE TABLE IF NOT EXISTS oc_budget_import_rule (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT       NOT NULL,
    pattern       VARCHAR(200) NOT NULL,
    category_id   BIGINT       NOT NULL,
    hits          INTEGER      NOT NULL,
    active        BOOLEAN      NOT NULL,
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_import_rule_user
    ON oc_budget_import_rule (user_id, active);
