-- ============================================================================
-- LINEA BASE: el esquema TAL Y COMO ESTA HOY
-- ============================================================================
--
-- Volcado literal del DDL que Hibernate venia generando con ddl-auto=update.
-- No cambia nada; solo deja de depender de lo que Hibernate decida al arrancar.
--
-- Sobre la base de datos que ya existe este fichero NO se ejecuta:
-- baseline-on-migrate=true da la version 1 por aplicada y Flyway sigue por la
-- V2. Solo corre entero en una instalacion limpia o en el H2 de las pruebas.
--
-- Un detalle: en la base que creo ddl-auto=update las claves llevan bigserial
-- (columna + secuencia); aqui se declaran GENERATED BY DEFAULT AS IDENTITY,
-- que es lo mismo para Hibernate y para la validacion del esquema y ademas
-- vale igual en PostgreSQL y en H2. Solo se nota en una instalacion nueva; la
-- base que ya existe conserva sus secuencias intactas porque este fichero no
-- corre sobre ella.
--
-- Las clausulas CHECK de los enums son las que genera Hibernate: si algun dia
-- se anade un valor a PlanType o a SessionStatus hace falta una migracion
-- nueva que las actualice, porque aqui no se regeneran solas.
-- ============================================================================

CREATE TABLE oc_fasting_plan_config (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id              BIGINT       NOT NULL,
    plan_type            VARCHAR(255) NOT NULL CHECK (plan_type IN
                             ('PLAN_12_12', 'PLAN_14_10', 'PLAN_16_8',
                              'PLAN_18_6', 'PLAN_20_4', 'CUSTOM')),
    fasting_hours        INTEGER      NOT NULL,
    eating_hours         INTEGER      NOT NULL,
    suggested_start_time VARCHAR(5),
    reminders_enabled    BOOLEAN      NOT NULL,
    active               BOOLEAN      NOT NULL,
    created_at           TIMESTAMP(6),
    updated_at           TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_fasting_session (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT       NOT NULL,
    plan_config_id  BIGINT,
    start_time      TIMESTAMP(6) NOT NULL,
    target_end_time TIMESTAMP(6) NOT NULL,
    actual_end_time TIMESTAMP(6),
    fasting_hours   INTEGER      NOT NULL,
    status          VARCHAR(255) NOT NULL CHECK (status IN
                        ('IN_PROGRESS', 'COMPLETED', 'INCOMPLETE', 'CANCELLED')),
    active          BOOLEAN      NOT NULL,
    created_at      TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_fasting_achievement (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT       NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    icon        VARCHAR(10),
    unlocked_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE oc_fasting_water_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT  NOT NULL,
    log_date     DATE    NOT NULL,
    glasses      INTEGER NOT NULL,
    goal_glasses INTEGER NOT NULL,
    created_at   TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX idx_plan_user_active ON oc_fasting_plan_config (user_id, active);
CREATE INDEX idx_session_user_status ON oc_fasting_session (user_id, status, active);
CREATE INDEX idx_session_user_start ON oc_fasting_session (user_id, start_time, active);
CREATE INDEX idx_achievement_user ON oc_fasting_achievement (user_id);
CREATE INDEX idx_water_user_date ON oc_fasting_water_log (user_id, log_date);
