-- ============================================================================
-- LINEA BASE: el esquema TAL Y COMO ESTA HOY
-- ============================================================================
--
-- Volcado literal del DDL que Hibernate venia generando con ddl-auto=update.
-- No cambia nada; solo deja de depender de lo que Hibernate decida al arrancar.
--
-- Sobre la base de datos que ya existe este fichero NO se ejecuta:
-- baseline-on-migrate=true da la version 1 por aplicada y Flyway sigue por la
-- V2. Solo corre entero en una instalacion limpia o en el H2 de las pruebas.
--
-- Un detalle: en la base que creo ddl-auto=update las claves llevan bigserial
-- (columna + secuencia); aqui se declaran GENERATED BY DEFAULT AS IDENTITY,
-- que es lo mismo para Hibernate y para la validacion del esquema y ademas
-- vale igual en PostgreSQL y en H2. Solo se nota en una instalacion nueva; la
-- base que ya existe conserva sus secuencias intactas porque este fichero no
-- corre sobre ella.
-- ============================================================================

CREATE TABLE oc_auth_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR(100) NOT NULL,
    email            VARCHAR(150) NOT NULL UNIQUE,
    password         VARCHAR(255) NOT NULL,
    budget_start_day INTEGER      NOT NULL,
    active           BOOLEAN      NOT NULL,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    PRIMARY KEY (id)
);
