server.port=8823
server.servlet.context-path=/oh-churus
spring.application.name=budget-service

eureka.instance.preferIpAddress=true
spring.cloud.discovery.enabled=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/budget_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:OhChurus2026}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

eureka.client.serviceUrl.defaultZone=http://discovery-service:8760/eureka

secret=${SECRET:ohchurus@secret.key}
expired-time=${EXP_TIME:864000000}

app.currency=COP
app.decimal-places=0

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
